services:
  saveenv:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-4001}:4001"
    environment:
      - DATABASE_URL=postgresql://saveenv:saveenv@postgres:5432/saveenv
      - PORT=4001
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-} #example: change-this-in-production
      - DOMAIN=localhost # or your domain example: https://saveenv.com
       #caso queira usar resend para enviar emails, use as variaveis abaixo
      - RESEND_KEY=${RESEND_KEY:-} #example: resend-key-here
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL:-} #example: Saveenv <noreply@contact.saveenv.com>
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - saveenv-network

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=saveenv
      - POSTGRES_PASSWORD=saveenv
      - POSTGRES_DB=saveenv
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - saveenv-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saveenv"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  saveenv-network:
    driver: bridge
